server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/dycai?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&&serverTimezone=UTC
      username: root
      password: "088114"
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      min-idle: 10
      max-active: 1000
      max-wait: 3600000
      filters: stat,wall
      min-evictable-idle-time-millis: 3600000
  redis:
    host: localhost
    port: 6379
    password:
    database: 0