spring:
  application:
    name: dragon-fruit-system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dragon_fruit?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&&serverTimezone=UTC
    username: root
    password: 'xdy088114'
  redis:
    host: localhost
    port: 6379
    password: avicit
    database: 0
  profiles:
    active: dev
logging:
  config: classpath:logback-spring.xml
mybatis:
  mapper-locations: classpath:mapper/**/*.xml